# Generated by Django 2.2.6 on 2019-10-10 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='arrival_time',
            field=models.TimeField(default=0, verbose_name=datetime.time(3, 3, 57, 754077)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='departure_time',
            field=models.TimeField(default=0, verbose_name=datetime.time(3, 3, 57, 754077)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='train_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
