# Generated by Django 2.2.6 on 2019-10-10 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191011_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000-08:00'),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000-08:00'),
        ),
    ]
