# Generated by Django 2.2.6 on 2019-10-10 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191011_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.DateTimeField(verbose_name=datetime.time(3, 14, 4, 963373)),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.DateTimeField(verbose_name=datetime.time(3, 14, 4, 963373)),
        ),
    ]
