# Generated by Django 2.2.6 on 2019-10-10 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191011_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.DateTimeField(verbose_name=datetime.time(4, 43, 21, 721095)),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.DateTimeField(verbose_name=datetime.time(4, 43, 21, 721095)),
        ),
    ]
